[package]
name = "music-gen"
version = "0.1.0"
authors = ["Cody Bloemhard <cblmhrd@live.nl>"]
edition = "2018"

[lib]
name = "music_gen"
path = "src/lib.rs"

[[bin]]
name = "testbin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
fnrs = "0.1.4"
lapp = "0.4.0"
